version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - banking-network

  account-service:
    build: service/account-service
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/bank
    ports:
      - "8081:8081"
    networks:
      - banking-network

  transaction-service:
    build: service/transaction-service
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/bank
    ports:
      - "8082:8082"
    networks:
      - banking-network

networks:
  banking-network:
    driver: bridge
